export const
	LOGGEDIN = 'LOGGEDIN',
	LOGGEDOUT = 'LOGGEDOUT',
	LOGIN_ERROR = 'LOGIN_ERROR',
	SWITCH_PAGE = 'SWITCH_PAGE',
	COURSES_LOADED = 'COURSES_LOADED',
	SET_CONFIG = 'SET_CONFIG',


	DUMMY = 'DUMMY';
